import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import './AppShell.css';

export default function AppShell({ children, activeNav = 'projects', onNavChange }) {
  const navigate       = useNavigate();
  const { user, logout } = useAuth();

  const handleSignOut = () => { logout(); navigate('/login'); };

  const initials = user?.name
    ? user.name.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase()
    : 'U';

  const displayName  = user?.name       || 'IndiGo User';
  const displayEmail = user?.email      || '';
  const department   = user?.department || 'Digital';

  return (
    <div className="shell-root">
      <div className="shell-warning-banner">
        <span className="shell-warn-icon">&#9888;</span>
        All creatives generated by this app must be reviewed and approved by the Marketing team before being used in any campaign or published externally.
      </div>

      <header className="shell-navbar">
        <div className="shell-nav-left">
          <div className="shell-logo" onClick={() => navigate('/dashboard')} style={{ cursor: 'pointer' }}>
            <span className="shell-logo-plane">✈</span>
            <span className="shell-logo-text">6E Creative Studio</span>
          </div>
          <nav className="shell-nav-links">
            <button
              className={`shell-nav-link ${activeNav === 'projects' ? 'active' : ''}`}
              onClick={() => onNavChange ? onNavChange('projects') : navigate('/dashboard')}
            >
              <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.7" className="shell-nav-icon">
                <rect x="2" y="3" width="7" height="7" rx="1.5" />
                <rect x="11" y="3" width="7" height="7" rx="1.5" />
                <rect x="2" y="12" width="7" height="5" rx="1.5" />
                <rect x="11" y="12" width="7" height="5" rx="1.5" />
              </svg>
              Projects
            </button>
            <button
              className={`shell-nav-link ${activeNav === 'explore' ? 'active' : ''}`}
              onClick={() => onNavChange ? onNavChange('explore') : navigate('/dashboard')}
            >
              <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.7" className="shell-nav-icon">
                <circle cx="10" cy="10" r="8" />
                <path d="M13.5 6.5l-2.5 4-4 2.5 2.5-4 4-2.5z" />
              </svg>
              Explore
            </button>
          </nav>
        </div>

        <div className="shell-nav-right">
          <div className="shell-user-info">
            <div className="shell-user-avatar">{initials}</div>
            <div className="shell-user-details">
              <span className="shell-user-name">{displayName} ({department})</span>
              <span className="shell-user-email">{displayEmail}</span>
            </div>
          </div>
          <button className="shell-signout-btn" onClick={handleSignOut}>
            <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" className="shell-signout-icon">
              <path d="M13 5l4 5-4 5M17 10H7" strokeLinecap="round" strokeLinejoin="round" />
              <path d="M7 3H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h3" strokeLinecap="round" />
            </svg>
            Sign out
          </button>
        </div>
      </header>

      {children}
    </div>
  );
}
